//! File-level checks for `shadow.rs` restore/rewind.

#[path = "../../build_stabilize.rs"]
mod build_stabilize;

use build_stabilize::{
    SHADOW_RS_OUTPUT, mtime_before_script_start, stabilize_shadow_rs_output, strip_build_time,
};
use std::path::{Path, PathBuf};
use std::time::{SystemTime, UNIX_EPOCH};

const COMMIT_ABC: &[u8] = b"// Code automatically generated by `shadow-rs`
// Generation time: Thu, 01 Jan 2026 00:00:00 +0000

pub const SHORT_COMMIT: &str = \"abc\";
pub const BUILD_TIME: &str = \"2026-01-01 00:00:00\";
";

const COMMIT_ABC_LATER: &[u8] = b"// Code automatically generated by `shadow-rs`
// Generation time: Fri, 02 Jan 2026 12:00:00 +0000

pub const SHORT_COMMIT: &str = \"abc\";
pub const BUILD_TIME: &str = \"2026-01-02 12:00:00\";
";

const COMMIT_DEF: &[u8] = b"// Code automatically generated by `shadow-rs`
// Generation time: Fri, 02 Jan 2026 12:00:00 +0000

pub const SHORT_COMMIT: &str = \"def\";
pub const BUILD_TIME: &str = \"2026-01-02 12:00:00\";
";

struct Scratch(PathBuf);

impl Scratch {
    fn new() -> Self {
        let dir = Path::new(env!("CARGO_TARGET_TMPDIR")).join(format!(
            "nu-cmd-lang-shadow-rs-{}-{}",
            std::process::id(),
            SystemTime::now()
                .duration_since(UNIX_EPOCH)
                .expect("system clock is after the Unix epoch")
                .as_nanos()
        ));
        std::fs::create_dir_all(&dir).expect("create scratch dir");
        Self(dir)
    }

    fn shadow_path(&self) -> PathBuf {
        self.0.join(SHADOW_RS_OUTPUT)
    }
}

impl Drop for Scratch {
    fn drop(&mut self) {
        let _ = std::fs::remove_dir_all(&self.0);
    }
}

fn write_fresh(path: &Path, contents: &[u8]) -> SystemTime {
    std::fs::write(path, contents).expect("write shadow.rs");
    let now = SystemTime::now();
    let file = std::fs::File::options()
        .write(true)
        .open(path)
        .expect("open shadow.rs");
    file.set_modified(now).expect("set shadow.rs mtime to now");
    now
}

fn modified(path: &Path) -> SystemTime {
    path.metadata()
        .expect("stat shadow.rs")
        .modified()
        .expect("shadow.rs mtime")
}

#[test]
fn strip_build_time_ignores_generation_clock() {
    assert_eq!(
        strip_build_time(COMMIT_ABC),
        strip_build_time(COMMIT_ABC_LATER)
    );
    assert_ne!(strip_build_time(COMMIT_ABC), strip_build_time(COMMIT_DEF));
}

#[test]
fn first_write_rewinds_mtime_and_keeps_bytes() {
    let scratch = Scratch::new();
    let path = scratch.shadow_path();
    let written_at = write_fresh(&path, COMMIT_ABC);

    stabilize_shadow_rs_output(&path, None);

    assert_eq!(std::fs::read(&path).expect("read shadow.rs"), COMMIT_ABC);
    let mtime = modified(&path);
    assert!(
        mtime < written_at,
        "mtime should be older than the write, got {mtime:?} >= {written_at:?}"
    );
    if let Some(floor) = mtime_before_script_start() {
        assert_eq!(mtime, floor);
    }
}

#[test]
fn time_only_change_restores_previous_bytes_and_rewinds_mtime() {
    let scratch = Scratch::new();
    let path = scratch.shadow_path();
    let written_at = write_fresh(&path, COMMIT_ABC_LATER);

    stabilize_shadow_rs_output(&path, Some(COMMIT_ABC));

    assert_eq!(std::fs::read(&path).expect("read shadow.rs"), COMMIT_ABC);
    let mtime = modified(&path);
    assert!(
        mtime < written_at,
        "mtime should be older than the write, got {mtime:?} >= {written_at:?}"
    );
}

#[test]
fn real_content_change_keeps_regenerated_file() {
    let scratch = Scratch::new();
    let path = scratch.shadow_path();
    let written_at = write_fresh(&path, COMMIT_DEF);

    stabilize_shadow_rs_output(&path, Some(COMMIT_ABC));

    assert_eq!(std::fs::read(&path).expect("read shadow.rs"), COMMIT_DEF);
    assert_eq!(modified(&path), written_at);
}
