//! Every `Example` of every built-in command must parse.
//!
//! `tests/corpus/snippets/nu-command-examples.json` is generated by
//! `tools/scripts/extract-corpus.nu` from the `Example { example: ".." }`
//! literals in the command crates of a Nushell checkout: the official
//! usage of every command, in the syntax the Nushell team writes. Regenerate
//! it when the checkout moves. `book.json` (the book's code blocks) is not
//! asserted here because it contains prompts and output; the `differential`
//! harness compares both parsers on it instead.
#![allow(clippy::unwrap_used, clippy::format_push_string, reason = "tests may panic on failure")]

use nu_winnow_parser::{ParseConfig, parse_lenient};
use serde::Deserialize;

#[derive(Deserialize)]
struct Snippet {
    origin: String,
    snippet: String,
}

fn snippets(name: &str) -> Vec<Snippet> {
    let path = format!("{}/tests/corpus/snippets/{name}", env!("CARGO_MANIFEST_DIR"));
    let text = std::fs::read_to_string(&path).unwrap_or_else(|e| panic!("cannot read {path}: {e}"));
    serde_json::from_str(&text).unwrap_or_else(|e| panic!("{path} is not a snippet list: {e}"))
}

#[test]
fn every_command_example_parses() {
    let config = ParseConfig::new();
    let list = snippets("nu-command-examples.json");
    assert!(list.len() > 1500, "expected the extracted examples, found {}", list.len());
    let mut failures = Vec::new();
    for s in &list {
        let (_, diagnostics) = parse_lenient(&s.snippet, &config);
        if let Some(d) = diagnostics.first() {
            failures.push(format!("{} :: {:?}\n{}", s.origin, s.snippet, d.render(&s.snippet, None)));
        }
    }
    assert!(
        failures.is_empty(),
        "{} of {} command examples do not parse:\n{}",
        failures.len(),
        list.len(),
        failures.join("\n")
    );
}
