FROM rust:1.37-slim

# docker build -t nushell/nu-base .
# docker run -it nushell/nu-base

ENV DEBIAN_FRONTEND noninteractive
RUN apt-get update && apt-get install -y libssl-dev \
    libxcb-composite0-dev \
    libx11-dev \
    pkg-config && \
    mkdir -p /code

ADD . /code
WORKDIR /code
RUN cargo build --release && cargo run --release && \
    cp target/release/nu /usr/local/bin
ENTRYPOINT ["nu"]
