pub(crate) mod value;

mod add;
mod get_col;
mod get_row;
mod identity;
mod into_nu;
mod map;
mod matrix_;
mod max;
mod mean;
mod multiply;
mod reduce;
mod reshape;
mod scale;
mod set_col;
mod set_row;
mod subtract;
mod sum;
mod transpose;
mod zeros;

pub use add::MatrixAdd;
pub use get_col::MatrixGetCol;
pub use get_row::MatrixGetRow;
pub use identity::MatrixIdentity;
pub use into_nu::MatrixIntoNu;
pub use map::MatrixMap;
pub use matrix_::Matrix;
pub use max::MatrixMax;
pub use mean::MatrixMean;
pub use multiply::MatrixMultiply;
pub use reduce::MatrixReduce;
pub use reshape::MatrixReshape;
pub use scale::MatrixScale;
pub use set_col::MatrixSetCol;
pub use set_row::MatrixSetRow;
pub use subtract::MatrixSubtract;
pub use sum::MatrixSum;
pub use transpose::MatrixTranspose;
pub use value::MatrixValue;
pub use zeros::MatrixZeros;
