mod abs;
mod avg;
mod ceil;
mod eval;
mod floor;
pub mod math_;
mod max;
mod median;
mod min;
mod mode;
mod product;
mod reducers;
mod round;
mod sqrt;
mod stddev;
mod sum;
mod utils;
mod variance;

pub use abs::SubCommand as MathAbs;
pub use avg::SubCommand as MathAvg;
pub use ceil::SubCommand as MathCeil;
pub use eval::SubCommand as MathEval;
pub use floor::SubCommand as MathFloor;
pub use math_::MathCommand as Math;
pub use max::SubCommand as MathMax;
pub use median::SubCommand as MathMedian;
pub use min::SubCommand as MathMin;
pub use mode::SubCommand as MathMode;
pub use product::SubCommand as MathProduct;
pub use round::SubCommand as MathRound;
pub use sqrt::SubCommand as MathSqrt;
pub use stddev::SubCommand as MathStddev;
pub use sum::SubCommand as MathSum;
pub use variance::SubCommand as MathVariance;
