mod abs;
mod avg;
mod ceil;
mod dot;
mod floor;
mod log;
mod magnitude;
pub mod math_;
mod max;
mod median;
mod min;
mod mode;
mod product;
mod reducers;
mod round;
mod sqnorm;
mod sqrt;
mod stddev;
mod sum;
mod utils;
mod variance;
mod vcos;
mod vsin;

pub use abs::SubCommand as MathAbs;
pub use avg::SubCommand as MathAvg;
pub use ceil::SubCommand as MathCeil;
pub use dot::SubCommand as MathDot;
pub use floor::SubCommand as MathFloor;
pub use magnitude::SubCommand as MathMagnitude;
pub use math_::MathCommand as Math;
pub use max::SubCommand as MathMax;
pub use median::SubCommand as MathMedian;
pub use min::SubCommand as MathMin;
pub use mode::SubCommand as MathMode;
pub use product::SubCommand as MathProduct;
pub use round::SubCommand as MathRound;
pub use sqnorm::SubCommand as MathSqnorm;
pub use sqrt::SubCommand as MathSqrt;
pub use stddev::SubCommand as MathStddev;
pub use sum::SubCommand as MathSum;
pub use variance::SubCommand as MathVariance;
pub use vcos::SubCommand as MathVcos;
pub use vsin::SubCommand as MathVsin;

pub use self::log::SubCommand as MathLog;
