#!/bin/sh

set -e

case "$1" in
    upgrade|failed-upgrade|abort-install|abort-upgrade)
	;;
    remove|purge|disappear)
	if which remove-shell >/dev/null && [ -f /etc/shells ]; then
	    remove-shell /usr/bin/nu
	fi
	;;
    *)
        echo "postrm called with unknown argument \`$1'" >&2
        exit 1
	;;
esac
