#!/usr/bin/env nu
# Generate `src/builtin_commands.rs`: every command a fresh `nu` resolves at
# the top level, with its nu-protocol `CommandType`, as the harness's
# nu-parser knows them.
#
#   nu tools/scripts/gen-builtin-commands.nu            # rewrite the file
#   nu tools/scripts/gen-builtin-commands.nu --check    # exit 1 when it is stale
#
# The names come from `tools/nushell-harness`'s `builtin-commands` binary,
# whose engine is the `nu` binary's (`src/command_context.rs`, with the
# default features and the standard library's prelude, and no plugins), so
# the parser and the differential test's nu-parser always agree on which
# commands exist. Regenerate when the enclosing checkout gains or loses commands.

# The nushell commit the harness is built from: the enclosing checkout, which
# its path dependencies point at.
def harness-commit [harness: path]: nothing -> string {
    git -C $harness rev-parse HEAD | str trim | str substring 0..8
}

# The source with the nushell commit in its header masked: the commit changes
# with every commit, while the commands stay the same.
def without-commit []: string -> string {
    str replace --regex 'at nushell `[0-9a-f]+`' 'at nushell `<commit>`'
}

# The Rust source of `src/builtin_commands.rs`.
def render [commit: string, commands: table<name: string, type: string, row_condition: string>]: nothing -> string {
    let entries = $commands | each {|c| $"    \(\"($c.name)\", ($c.type)\),"}
    let row_conditions = $commands | where row_condition == "true" | each {|c| $"    \"($c.name)\","}
    [
        "//! Every command a fresh `nu` resolves at the top level, with its kind: the"
        "//! built-in and keyword commands of the `nu` binary and the standard"
        $"//! library's prelude, at nushell `($commit)`. Used, when the"
        "//! `builtin-commands` feature is enabled, to resolve multi-word command names"
        "//! such as `str trim`, to tell a known command from an external one, to"
        "//! check that `%name` names a built-in command, and to parse the arguments of"
        "//! a command taking a row condition (`any`, `take while`) as one condition."
        "//!"
        "//! Generated by `tools/scripts/gen-builtin-commands.nu`; do not edit."
        ""
        "use crate::CommandType::{self, *};"
        ""
        "/// Every command name with its kind, sorted by name."
        "pub static BUILTIN_COMMANDS: &[(&str, CommandType)] = &["
        ...$entries
        "];"
        ""
        "/// The commands whose first positional parameter is a row condition, sorted by name."
        "#[rustfmt::skip]"
        "pub static ROW_CONDITION_COMMANDS: &[&str] = &["
        ...$row_conditions
        "];"
        ""
    ] | str join "\n"
}

# Rewrite src/builtin_commands.rs, or with --check report whether it is current.
def main [
    --check    # do not write; exit 1 when the file is stale
]: nothing -> nothing {
    let root = $env.FILE_PWD | path join ../.. | path expand
    let harness = $root | path join tools/nushell-harness
    let target = $root | path join src/builtin_commands.rs
    # Build into the workspace's target directory, where the other harness binaries are.
    let cargo_target = $env.CARGO_TARGET_DIR? | default ($root | path join ../../target) | path expand
    let run = with-env {CARGO_TARGET_DIR: $cargo_target} {
        ^cargo run --quiet --release --manifest-path ($harness | path join Cargo.toml) --bin builtin-commands | complete
    }
    if $run.exit_code != 0 {
        error make {msg: $"builtin-commands failed:\n($run.stderr)"}
    }
    let commands = $run.stdout | lines | parse "{name}\t{type}\t{row_condition}" | sort-by name
    let source = render (harness-commit $harness) $commands
    let current = if ($target | path exists) { open --raw $target } else { "" }
    if $check {
        # The file is current when it lists the same commands, whatever commit it was
        # generated at: committing a regenerated file moves the commit again.
        if ($current | without-commit) != ($source | without-commit) {
            print "src/builtin_commands.rs is stale; run `nu tools/scripts/gen-builtin-commands.nu`"
            exit 1
        }
        print $"($commands | length) commands; src/builtin_commands.rs is current"
        return
    }
    $source | save -f $target
    print $"($commands | length) commands; wrote src/builtin_commands.rs"
}
