[package]
authors.workspace = true
description = "Nushell's parser"
repository = "https://github.com/nushell/nushell/tree/main/crates/nu-parser"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
name = "nu-parser"
version.workspace = true
exclude = ["/fuzz"]

[lib]
bench = false

[lints]
workspace = true

[dependencies]
nu-engine.workspace = true
nu-path.workspace = true
nu-plugin-engine = { workspace = true, optional = true }
nu-protocol.workspace = true
nu-utils.workspace = true
nu-experimental.workspace = true

bytesize = { workspace = true }
chrono = { default-features = false, features = ['std'], workspace = true }
itertools = { workspace = true }
log = { workspace = true }
lz4_flex = { workspace = true, features = ["std", "safe-encode", "safe-decode", "checked-decode"] }
memchr = { workspace = true }
pathdiff = { workspace = true }
postcard = { workspace = true, features = ["use-std"] }
semver = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }

[dev-dependencies]
rstest = { workspace = true, default-features = false }

[features]
plugin = ["nu-plugin-engine", "nu-engine/plugin"]
