[package]
authors.workspace = true
description = "Composable terminal UI commands for Nushell"
repository = "https://github.com/nushell/nushell/tree/main/crates/nu-tui"
edition.workspace = true
license.workspace = true
name = "nu-tui"
rust-version.workspace = true
version.workspace = true

[lib]
bench = false

[[test]]
name = "tests"
path = "tests/main.rs"
harness = false

[lints]
workspace = true

[dependencies]
nu-protocol = { workspace = true, features = ["os"] }
nu-engine = { workspace = true, features = ["os"] }
nu-command = { workspace = true, features = ["os"] }
nu-color-config.workspace = true
nu-explore.workspace = true
nu-utils.workspace = true
nu-ansi-term.workspace = true

ansi-str = { workspace = true }
crossterm = { workspace = true }
lscolors = { workspace = true, default-features = false, features = [
    "nu-ansi-term",
] }
mime_guess = { workspace = true }
nucleo-matcher = { workspace = true }
ratatui = { workspace = true }
serde = { workspace = true, features = ["derive"] }
typetag = "0.2"

[dev-dependencies]
nu-cmd-lang = { workspace = true, features = ["os"] }
nu-test-support = { path = "../nu-test-support", features = ["os"] }
