on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
  push:
    branches:
      - main
      - 'patch-release-*'

name: Continuous Integration

permissions:
  contents: read

env:
  # Regular env variables
  NU_LOG_LEVEL: DEBUG
  NU_TEST_SKIP_DEPS_BUILD: true
  NUSHELL_CARGO_PROFILE: ci

  # Records for dynamic selection
  OS_NAMES: '{"Windows":"windows","Linux":"linux","macOS":"macos"}'
  ARCH_NAMES: '{"X86":"x86","X64":"x86_64","ARM":"arm","ARM64":"aarch64"}'

  # Job values
  LINUX_RUNNER: &runner_linux incredibuild-ubuntu-2204
  MACOS_RUNNER: &runner_macos macos-latest
  WINDOWS_RUNNER: &runner_windows incredibuild-windows-2022
  LINUX_TARGET: &target_linux x86_64-unknown-linux-gnu
  MACOS_TARGET: &target_macos x86_64-apple-darwin
  WINDOWS_TARGET: &target_windows x86_64-pc-windows-msvc
  JOB_IF: &job_if >- # Do not run CI on draft PRs or on the lower layers of stacked PRs
    !github.event.pull_request.draft &&
    (
      github.event.pull_request.stack == null ||
      github.event.pull_request.stack.position ==
        github.event.pull_request.stack.size
    )

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref && github.ref || github.run_id }}
  cancel-in-progress: true

jobs:
  catalog:
    if: false
    runs-on: *runner_linux
    steps:
      - &step_checkout_repo
        name: Checkout Repo
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - &step_setup_rust_toolchain
        name: Setup Rust Toolchain
        run: rustup target add ${{ env.target }}
        working-directory: ${{ env.working-directory || github.workspace }}
      - &step_cache_rust
        name: Cache Rust
        uses: Swatinem/rust-cache@6323deb102c322ba6fcbdcafc7e3dddab59af2b6 # v2.9.2
        with:
          workspaces: ${{ env.working-directory || github.workspace }} -> target
          cache-all-crates: true
          cache-workspace-crates: true
      - &step_fmt
        name: Fmt
        working-directory: ${{ env.working-directory || github.workspace }}
        run: |
          rustup component add rustfmt
          cargo fmt --all --check
      - &step_check
        name: Check
        working-directory: ${{ env.working-directory || github.workspace }}
        run: >-
          cargo --config "${{ github.workspace }}/.cargo/ci.toml" 
          check ${{ env.cargo-options || '--workspace --all-targets' }} 
          --profile ${{ env.profile || 'ci' }}
      - &step_clippy
        name: Clippy
        working-directory: ${{ env.working-directory || github.workspace }}
        run: >-
          rustup component add clippy

          cargo --config "${{ github.workspace }}/.cargo/ci.toml" 
          clippy ${{ env.cargo-options || '--workspace --all-targets' }} 
          --profile ${{ env.profile || 'ci' }} 
          -- -D warnings
      - &step_build
        name: Build
        working-directory: ${{ env.working-directory || github.workspace }}
        run: >-
          cargo --config "${{ github.workspace }}/.cargo/ci.toml" 
          build ${{ env.cargo-options || '--workspace --all-targets' }} 
          --profile ${{ env.profile || 'ci' }}
      - &step_test
        name: Test
        working-directory: ${{ env.working-directory || github.workspace }}
        run: >-
          cargo --config "${{ github.workspace }}/.cargo/ci.toml"
          test ${{ env.cargo-options || '--workspace --all-targets' }}
          --profile ${{ env.profile || 'ci' }}
      - &step_doctest
        name: Doctest
        working-directory: ${{ env.working-directory || github.workspace }}
        run: >-
          cargo --config "${{ github.workspace }}/.cargo/ci.toml" 
          test --workspace --doc 
          --profile ${{ env.profile || 'ci' }}
      - &step_test_std
        name: Test Std
        run: >-
          cargo run -- -n -c 
          'use crates/nu-std/testing.nu; testing run-tests --path crates/nu-std'
      - &step_setup_python
        name: Setup Python
        uses: actions/setup-python@5fda3b95a4ea91299a34e894583c3862153e4b97 # v7.0.0
        with:
          python-version: "3.10"
      - &step_install_virtualenv
        name: Install virtualenv
        run: pip install virtualenv
      - &step_test_virtualenv
        name: Test virtualenv
        run: cargo run -- scripts/test_virtualenv.nu
      - &step_upload_artifacts
        name: Upload Artifacts
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: &artifact_name >-
            ${{ format('nu-{0}-{1}-{2}',
              github.event.number || github.ref_name,
              fromJSON(env.OS_NAMES)[runner.os],
              fromJSON(env.ARCH_NAMES)[runner.arch]) }}
          path: |
            ${{ format('{0}/{1}/nu',
              env.working-directory || github.workspace,
              env.profile || 'ci') }}
            ${{ format('{0}/{1}/nu.exe',
              env.working-directory || github.workspace,
              env.profile || 'ci') }}
          retention-days: 14
      - &step_assert_clean_repo
        name: Assert Clean Repo
        run: git diff --quiet && git diff --cached --quiet


  linux_root:
    name: linux/root
    runs-on: *runner_linux
    if: *job_if
    env:
      target: *target_linux
    steps: &steps_root
      - *step_checkout_repo
      - *step_setup_rust_toolchain
      - *step_cache_rust
      - *step_fmt
      - *step_check
      - *step_clippy
      - *step_build
      - *step_test
      - *step_doctest
      - *step_test_std
      - *step_setup_python
      - *step_install_virtualenv
      - *step_test_virtualenv
      - *step_upload_artifacts
      - *step_assert_clean_repo

  windows_root:
    name: windows/root
    runs-on: *runner_windows
    if: *job_if
    env:
      target: *target_windows
    steps: *steps_root

  macos_root:
    name: macos/root
    runs-on: *runner_macos
    if: *job_if
    env:
      target: *target_macos
    steps: *steps_root

  wasm_root:
    name: wasm/root
    runs-on: *runner_linux
    if: *job_if
    env:
      target: wasm32-unknown-unknown
      cargo-options: >-
        --no-default-features
        --target wasm32-unknown-unknown
        -p nu-cmd-base
        -p nu-cmd-extra
        -p nu-cmd-lang
        -p nu-color-config
        -p nu-command
        -p nu-derive-value
        -p nu-engine
        -p nu-glob
        -p nu-json
        -p nu-parser
        -p nu-path
        -p nu-pretty-hex
        -p nu-protocol
        -p nu-std
        -p nu-system
        -p nu-table
        -p nu-term-grid
        -p nu-utils
        -p nuon
    steps:
      - *step_checkout_repo
      - *step_setup_rust_toolchain
      - *step_cache_rust
      - *step_check
      - *step_build
      - *step_assert_clean_repo

  linux_nu-parser_fuzz:
    name: linux/nu-parser/fuzz
    runs-on: *runner_linux
    if: *job_if
    env:
      target: *target_linux
      working-directory: &wd_nu-parser_fuzz ${{ github.workspace }}/crates/nu-parser/fuzz
    steps: &steps_fuzz
      - *step_checkout_repo
      - *step_setup_rust_toolchain
      - *step_cache_rust
      - *step_fmt
      - *step_check
      - *step_clippy
      - *step_assert_clean_repo

  windows_nu-parser_fuzz:
    name: windows/nu-parser/fuzz
    runs-on: *runner_windows
    if: *job_if
    env:
      target: *target_windows
      working-directory: *wd_nu-parser_fuzz
    steps: *steps_fuzz

  macos_nu-parser_fuzz:
    name: macos/nu-parser/fuzz
    runs-on: *runner_macos
    if: *job_if
    env:
      target: *target_macos
      working-directory: *wd_nu-parser_fuzz
    steps: *steps_fuzz

  linux_nu-path_fuzz:
    name: linux/nu-path/fuzz
    runs-on: *runner_linux
    if: *job_if
    env:
      target: *target_linux
      working-directory: &wd_nu-path_fuzz ${{ github.workspace }}/crates/nu-path/fuzz
    steps: *steps_fuzz

  windows_nu-path_fuzz:
    name: windows/nu-path/fuzz
    runs-on: *runner_windows
    if: *job_if
    env:
      target: *target_windows
      working-directory: *wd_nu-path_fuzz
    steps: *steps_fuzz

  macos_nu-path_fuzz:
    name: macos/nu-path/fuzz
    runs-on: *runner_macos
    if: *job_if
    env:
      target: *target_macos
      working-directory: *wd_nu-path_fuzz
    steps: *steps_fuzz
