on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
  push:
    branches:
      - main
      - 'patch-release-*'

name: Continuous Integration

permissions:
  contents: read

env:
  NU_BUILD_PR: ${{ github.event.pull_request.html_url }}
  NU_LOG_LEVEL: DEBUG
  NU_TEST_SKIP_DEPS_BUILD: true
  NUSHELL_CARGO_PROFILE: ci

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref && github.ref || github.run_id }}
  cancel-in-progress: true

jobs:
  root:
    name: ${{ matrix.platform.name }} / root
    runs-on: ${{ matrix.platform.runner }}
    # Do not run CI on draft PRs or on the lower layers of stacked PRs
    if: &job_if >-
      !github.event.pull_request.draft &&
      (
        github.event.pull_request.stack == null ||
        github.event.pull_request.stack.position ==
          github.event.pull_request.stack.size
      )
    env:
      build-target: ${{ matrix.platform.target }}
      working-directory: ${{ github.workspace }}
      cargo-options: --workspace --all-targets
      profile: ci
    strategy:
      matrix:
        platform: &platforms
          - name: Linux
            runner: &runner_linux incredibuild-ubuntu-2204
            target: &target_linux x86_64-unknown-linux-gnu
          - name: Windows
            runner: &runner_windows incredibuild-windows-2022
            target: &target_windows x86_64-pc-windows-msvc
          - name: MacOS
            runner: &runner_macos macos-latest
            target: &target_macos x86_64-apple-darwin
    steps:

      - &step_checkout_repo
        name: Checkout Repo
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - &step_setup_rust_toolchain
        name: Setup Rust Toolchain
        run: rustup target add ${{ env.build-target }}
        working-directory: ${{ env.working-directory }}

      - &step_cache_rust
        name: Cache Rust
        uses: Swatinem/rust-cache@6323deb102c322ba6fcbdcafc7e3dddab59af2b6 # v2.9.2
        with:
          workspaces: ${{ env.working-directory }} -> target
          cache-all-crates: true
          cache-workspace-crates: true

      - &step_fmt
        name: Fmt
        working-directory: ${{ env.working-directory }}
        run: |
          rustup component add rustfmt
          cargo fmt --all --check

      - &step_check
        name: Check
        working-directory: ${{ env.working-directory }}
        run: >-
          cargo --config "${{ github.workspace }}/.cargo/ci.toml" 
          check ${{ env.cargo-options }} 
          --profile ${{ env.profile }}

      - &step_clippy
        name: Clippy
        working-directory: ${{ env.working-directory }}
        run: >-
          rustup component add clippy

          cargo --config "${{ github.workspace }}/.cargo/ci.toml" 
          clippy ${{ env.cargo-options }} 
          --profile ${{ env.profile }} 
          -- -D warnings

      - &step_build
        name: Build
        working-directory: ${{ env.working-directory }}
        run: >-
          cargo --config "${{ github.workspace }}/.cargo/ci.toml" 
          build ${{ env.cargo-options }} 
          --profile ${{ env.profile }}

      - &step_test
        name: Test
        working-directory: ${{ env.working-directory }}
        run: >-
          cargo --config "${{ github.workspace }}/.cargo/ci.toml"
          test ${{ env.cargo-options }}
          --profile ${{ env.profile }}

      - &step_doctest
        name: Doctest
        working-directory: ${{ env.working-directory }}
        run: >-
          cargo --config "${{ github.workspace }}/.cargo/ci.toml" 
          test --workspace --doc 
          --profile ${{ env.profile }}

      - &step_add_nushell_to_path
        name: Add Nushell to PATH
        shell: bash
        env:
          NU_HOME: ${{ env.working-directory }}/target/${{ env.profile }}
        run: printf '%s\n' "${NU_HOME}" >> "$GITHUB_PATH"

      - &step_test_std
        name: Test Std
        run: nu -n -c 'use crates/nu-std/testing.nu; testing run-tests --path crates/nu-std'

      - &step_setup_python
        name: Setup Python
        uses: actions/setup-python@5fda3b95a4ea91299a34e894583c3862153e4b97 # v7.0.0
        with:
          python-version: "3.10"

      - &step_install_virtualenv
        name: Install virtualenv
        run: pip install virtualenv

      - &step_test_virtualenv
        name: Test virtualenv
        run: nu scripts/test_virtualenv.nu

      - &step_upload_artifacts
        name: Upload Artifacts
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        env:
          OS_NAMES: '{"Windows":"windows","Linux":"linux","macOS":"macos"}'
          ARCH_NAMES: '{"X86":"x86","X64":"x86_64","ARM":"arm","ARM64":"aarch64"}'
        with:
          name: &artifact_name >-
            ${{ format('nu-{0}-{1}-{2}',
              github.event.number || github.ref_name,
              fromJSON(env.OS_NAMES)[runner.os],
              fromJSON(env.ARCH_NAMES)[runner.arch]) }}
          path: |
            ${{ format('{0}/target/{1}/nu',
              env.working-directory || github.workspace,
              env.profile || 'ci') }}
            ${{ format('{0}/target/{1}/nu.exe',
              env.working-directory || github.workspace,
              env.profile || 'ci') }}
          retention-days: 14

      - &step_assert_clean_repo
        name: Assert Clean Repo
        shell: bash
        run: test -z "$(git status --porcelain)"

  root_wasm:
    name: WASM / root
    runs-on: *runner_linux
    if: *job_if
    env:
      build-target: wasm32-unknown-unknown
      working-directory: ${{ github.workspace }}
      profile: ci
      cargo-options: >-
        --no-default-features
        --target wasm32-unknown-unknown
        -p nu-cmd-base
        -p nu-cmd-extra
        -p nu-cmd-lang
        -p nu-color-config
        -p nu-command
        -p nu-derive-value
        -p nu-engine
        -p nu-glob
        -p nu-json
        -p nu-parser
        -p nu-path
        -p nu-pretty-hex
        -p nu-protocol
        -p nu-std
        -p nu-system
        -p nu-table
        -p nu-term-grid
        -p nu-utils
        -p nuon
    steps:
      - *step_checkout_repo
      - *step_setup_rust_toolchain
      - *step_cache_rust
      - *step_check
      - *step_build
      - *step_assert_clean_repo

  fuzz:
    name: ${{ matrix.platform.name }} / ${{ matrix.crate }} / fuzz
    runs-on: ${{ matrix.platform.runner }}
    if: *job_if
    env:
      build-target: ${{ matrix.platform.target }}
      working-directory: ${{ github.workspace }}/crates/${{ matrix.crate }}/fuzz
      profile: dev
      cargo-options: --all-targets
    strategy:
      matrix:
        platform: *platforms
        crate:
          - nu-parser
          - nu-path
    steps:
      - *step_checkout_repo
      - *step_setup_rust_toolchain
      - *step_cache_rust
      - *step_fmt
      - *step_check
      - *step_clippy
      - *step_assert_clean_repo
