name: Comment on changes to the config
on:
  pull_request_target:
    paths:
      - 'crates/nu-protocol/src/config/**'
permissions:
  # Find and post the config reminder comment on the pull request.
  issues: write
  pull-requests: write

jobs:
  comment:
    runs-on: ubuntu-latest
    steps:
    - name: Check if there is already a bot comment
      uses: peter-evans/find-comment@b30e6a3c0ed37e7c023ccd3f1db5c6c0b0c23aad # v4.0.0
      id: fc
      with:
        issue-number: ${{ github.event.pull_request.number }}
        comment-author: 'github-actions[bot]'
        body-includes: Hey, just a bot checking in!
    - name: Create comment if there is not
      if: steps.fc.outputs.comment-id == ''
      uses: peter-evans/create-or-update-comment@e8674b075228eee787fea43ef493e45ece1004c9 # v5.0.0
      with:
        issue-number: ${{ github.event.pull_request.number }}
        body: |
          Hey, just a bot checking in! You edited files related to the configuration.
          If you changed any of the default values or added a new config option, don't forget to update the [`doc_config.nu`](https://github.com/nushell/nushell/blob/main/crates/nu-config/default_files/doc_config.nu) which documents the options for our users including the defaults provided by the Rust implementation.
          If you didn't make a change here, you can just ignore me.
